// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: prototype/service.proto

package prototype

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AddressRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AddressRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddressRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AddressRequestMultiError,
// or nil if none found.
func (m *AddressRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AddressRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetAddress()) != 42 {
		err := AddressRequestValidationError{
			field:  "Address",
			reason: "value length must be 42 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)

	}

	if len(errors) > 0 {
		return AddressRequestMultiError(errors)
	}
	return nil
}

// AddressRequestMultiError is an error wrapping multiple validation errors
// returned by AddressRequest.ValidateAll() if the designated constraints
// aren't met.
type AddressRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddressRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddressRequestMultiError) AllErrors() []error { return m }

// AddressRequestValidationError is the validation error returned by
// AddressRequest.Validate if the designated constraints aren't met.
type AddressRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddressRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddressRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddressRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddressRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddressRequestValidationError) ErrorName() string { return "AddressRequestValidationError" }

// Error satisfies the builtin error interface
func (e AddressRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddressRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddressRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddressRequestValidationError{}

// Validate checks the field values on NumRequest with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *NumRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NumRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in NumRequestMultiError, or
// nil if none found.
func (m *NumRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *NumRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetNum() < 0 {
		err := NumRequestValidationError{
			field:  "Num",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return NumRequestMultiError(errors)
	}
	return nil
}

// NumRequestMultiError is an error wrapping multiple validation errors
// returned by NumRequest.ValidateAll() if the designated constraints aren't met.
type NumRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NumRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NumRequestMultiError) AllErrors() []error { return m }

// NumRequestValidationError is the validation error returned by
// NumRequest.Validate if the designated constraints aren't met.
type NumRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NumRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NumRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NumRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NumRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NumRequestValidationError) ErrorName() string { return "NumRequestValidationError" }

// Error satisfies the builtin error interface
func (e NumRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNumRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NumRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NumRequestValidationError{}

// Validate checks the field values on HashRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *HashRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HashRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in HashRequestMultiError, or
// nil if none found.
func (m *HashRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *HashRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetHash()) != 66 {
		err := HashRequestValidationError{
			field:  "Hash",
			reason: "value length must be 66 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)

	}

	if len(errors) > 0 {
		return HashRequestMultiError(errors)
	}
	return nil
}

// HashRequestMultiError is an error wrapping multiple validation errors
// returned by HashRequest.ValidateAll() if the designated constraints aren't met.
type HashRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HashRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HashRequestMultiError) AllErrors() []error { return m }

// HashRequestValidationError is the validation error returned by
// HashRequest.Validate if the designated constraints aren't met.
type HashRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HashRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HashRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HashRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HashRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HashRequestValidationError) ErrorName() string { return "HashRequestValidationError" }

// Error satisfies the builtin error interface
func (e HashRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHashRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HashRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HashRequestValidationError{}

// Validate checks the field values on UTxOResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UTxOResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UTxOResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UTxOResponseMultiError, or
// nil if none found.
func (m *UTxOResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UTxOResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetData() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, UTxOResponseValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, UTxOResponseValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UTxOResponseValidationError{
					field:  fmt.Sprintf("Data[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return UTxOResponseMultiError(errors)
	}
	return nil
}

// UTxOResponseMultiError is an error wrapping multiple validation errors
// returned by UTxOResponse.ValidateAll() if the designated constraints aren't met.
type UTxOResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UTxOResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UTxOResponseMultiError) AllErrors() []error { return m }

// UTxOResponseValidationError is the validation error returned by
// UTxOResponse.Validate if the designated constraints aren't met.
type UTxOResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UTxOResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UTxOResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UTxOResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UTxOResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UTxOResponseValidationError) ErrorName() string { return "UTxOResponseValidationError" }

// Error satisfies the builtin error interface
func (e UTxOResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUTxOResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UTxOResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UTxOResponseValidationError{}

// Validate checks the field values on StatusResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *StatusResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StatusResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in StatusResponseMultiError,
// or nil if none found.
func (m *StatusResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *StatusResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Error

	// no validation rules for Data

	if len(errors) > 0 {
		return StatusResponseMultiError(errors)
	}
	return nil
}

// StatusResponseMultiError is an error wrapping multiple validation errors
// returned by StatusResponse.ValidateAll() if the designated constraints
// aren't met.
type StatusResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StatusResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StatusResponseMultiError) AllErrors() []error { return m }

// StatusResponseValidationError is the validation error returned by
// StatusResponse.Validate if the designated constraints aren't met.
type StatusResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StatusResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StatusResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StatusResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StatusResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StatusResponseValidationError) ErrorName() string { return "StatusResponseValidationError" }

// Error satisfies the builtin error interface
func (e StatusResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStatusResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StatusResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StatusResponseValidationError{}

// Validate checks the field values on SendTxRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SendTxRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendTxRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SendTxRequestMultiError, or
// nil if none found.
func (m *SendTxRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SendTxRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetTx()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SendTxRequestValidationError{
					field:  "Tx",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SendTxRequestValidationError{
					field:  "Tx",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTx()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SendTxRequestValidationError{
				field:  "Tx",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SendTxRequestMultiError(errors)
	}
	return nil
}

// SendTxRequestMultiError is an error wrapping multiple validation errors
// returned by SendTxRequest.ValidateAll() if the designated constraints
// aren't met.
type SendTxRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendTxRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendTxRequestMultiError) AllErrors() []error { return m }

// SendTxRequestValidationError is the validation error returned by
// SendTxRequest.Validate if the designated constraints aren't met.
type SendTxRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendTxRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendTxRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendTxRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendTxRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendTxRequestValidationError) ErrorName() string { return "SendTxRequestValidationError" }

// Error satisfies the builtin error interface
func (e SendTxRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendTxRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendTxRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendTxRequestValidationError{}

// Validate checks the field values on ErrorResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ErrorResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ErrorResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ErrorResponseMultiError, or
// nil if none found.
func (m *ErrorResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ErrorResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Error

	if len(errors) > 0 {
		return ErrorResponseMultiError(errors)
	}
	return nil
}

// ErrorResponseMultiError is an error wrapping multiple validation errors
// returned by ErrorResponse.ValidateAll() if the designated constraints
// aren't met.
type ErrorResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ErrorResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ErrorResponseMultiError) AllErrors() []error { return m }

// ErrorResponseValidationError is the validation error returned by
// ErrorResponse.Validate if the designated constraints aren't met.
type ErrorResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ErrorResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ErrorResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ErrorResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ErrorResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ErrorResponseValidationError) ErrorName() string { return "ErrorResponseValidationError" }

// Error satisfies the builtin error interface
func (e ErrorResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sErrorResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ErrorResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ErrorResponseValidationError{}

// Validate checks the field values on BlockResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BlockResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BlockResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BlockResponseMultiError, or
// nil if none found.
func (m *BlockResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *BlockResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetBlock()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BlockResponseValidationError{
					field:  "Block",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BlockResponseValidationError{
					field:  "Block",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBlock()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BlockResponseValidationError{
				field:  "Block",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Error

	if len(errors) > 0 {
		return BlockResponseMultiError(errors)
	}
	return nil
}

// BlockResponseMultiError is an error wrapping multiple validation errors
// returned by BlockResponse.ValidateAll() if the designated constraints
// aren't met.
type BlockResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BlockResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BlockResponseMultiError) AllErrors() []error { return m }

// BlockResponseValidationError is the validation error returned by
// BlockResponse.Validate if the designated constraints aren't met.
type BlockResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BlockResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BlockResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BlockResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BlockResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BlockResponseValidationError) ErrorName() string { return "BlockResponseValidationError" }

// Error satisfies the builtin error interface
func (e BlockResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBlockResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BlockResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BlockResponseValidationError{}

// Validate checks the field values on TransactionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TransactionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TransactionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TransactionResponseMultiError, or nil if none found.
func (m *TransactionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *TransactionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetTx()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TransactionResponseValidationError{
					field:  "Tx",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TransactionResponseValidationError{
					field:  "Tx",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTx()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TransactionResponseValidationError{
				field:  "Tx",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Error

	if len(errors) > 0 {
		return TransactionResponseMultiError(errors)
	}
	return nil
}

// TransactionResponseMultiError is an error wrapping multiple validation
// errors returned by TransactionResponse.ValidateAll() if the designated
// constraints aren't met.
type TransactionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TransactionResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TransactionResponseMultiError) AllErrors() []error { return m }

// TransactionResponseValidationError is the validation error returned by
// TransactionResponse.Validate if the designated constraints aren't met.
type TransactionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TransactionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TransactionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TransactionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TransactionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TransactionResponseValidationError) ErrorName() string {
	return "TransactionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e TransactionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTransactionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TransactionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TransactionResponseValidationError{}

// Validate checks the field values on TransactionsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TransactionsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TransactionsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TransactionsResponseMultiError, or nil if none found.
func (m *TransactionsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *TransactionsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetTx() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, TransactionsResponseValidationError{
						field:  fmt.Sprintf("Tx[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, TransactionsResponseValidationError{
						field:  fmt.Sprintf("Tx[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return TransactionsResponseValidationError{
					field:  fmt.Sprintf("Tx[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Error

	if len(errors) > 0 {
		return TransactionsResponseMultiError(errors)
	}
	return nil
}

// TransactionsResponseMultiError is an error wrapping multiple validation
// errors returned by TransactionsResponse.ValidateAll() if the designated
// constraints aren't met.
type TransactionsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TransactionsResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TransactionsResponseMultiError) AllErrors() []error { return m }

// TransactionsResponseValidationError is the validation error returned by
// TransactionsResponse.Validate if the designated constraints aren't met.
type TransactionsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TransactionsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TransactionsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TransactionsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TransactionsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TransactionsResponseValidationError) ErrorName() string {
	return "TransactionsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e TransactionsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTransactionsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TransactionsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TransactionsResponseValidationError{}

// Validate checks the field values on NumberResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *NumberResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NumberResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in NumberResponseMultiError,
// or nil if none found.
func (m *NumberResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *NumberResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Result

	// no validation rules for Error

	if len(errors) > 0 {
		return NumberResponseMultiError(errors)
	}
	return nil
}

// NumberResponseMultiError is an error wrapping multiple validation errors
// returned by NumberResponse.ValidateAll() if the designated constraints
// aren't met.
type NumberResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NumberResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NumberResponseMultiError) AllErrors() []error { return m }

// NumberResponseValidationError is the validation error returned by
// NumberResponse.Validate if the designated constraints aren't met.
type NumberResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NumberResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NumberResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NumberResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NumberResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NumberResponseValidationError) ErrorName() string { return "NumberResponseValidationError" }

// Error satisfies the builtin error interface
func (e NumberResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNumberResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NumberResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NumberResponseValidationError{}
